name: Publish CLI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  publish-docker:
    runs-on: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and publish CLI image
        uses: http://forgejo:3000/andras/ci-actions/docker-publish@main
        with:
          context: frontend
          dockerfile: frontend/local-client-cli/Dockerfile
          image-suffix: -cli
          push: ${{ github.event_name != 'pull_request' }}
          token: ${{ secrets.GITHUB_TOKEN }}
