// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentWithCursors } from "./DocumentWithCursors";

export interface ClientCursors {
	userName: string;
	deviceId: string;
	documentsWithCursors: DocumentWithCursors[];
}
