// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorSpan } from "./CursorSpan";

export interface ClientCursors {
	userName: string;
	deviceId: string;
	cursors: Partial<Record<string, CursorSpan[]>>;
}
