// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateDocumentVersion {
    relative_path: string;
    force_merge: boolean | null;
    content: number[];
}
