// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientCursors } from "./ClientCursors";

export interface CursorPositionFromServer {
	clients: ClientCursors[];
}
