// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorSpan } from "./CursorSpan";

export interface CursorPositionFromClient {
	documentToCursors: Partial<Record<string, CursorSpan[]>>;
}
