// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersion } from "./DocumentVersion";
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";

/**
 * Response to an update document request.
 */
export type DocumentUpdateResponse =
	| ({ type: "FastForwardUpdate" } & DocumentVersionWithoutContent)
	| ({ type: "MergingUpdate" } & DocumentVersion);
