// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Like [`DocumentVersionWithoutContent`] but without the `relative_path`.
 * Used only in create/update responses where the client already tracks
 * the path locally (the server is the source of truth for the
 * document identity, not its path).
 */
export interface DocumentUpdateMetadata { vaultUpdateId: number, documentId: string, updatedDate: string, isDeleted: boolean, userId: string, deviceId: string, contentSize: number, }
