// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Like [`DocumentVersion`] but without the `relative_path`.
 * Used only in create/update responses when the server had to merge the
 * client's content with a newer remote version and therefore must echo
 * the merged content back.
 */
export interface DocumentUpdateMergedContent { vaultUpdateId: number, documentId: string, updatedDate: string, contentBase64: string, isDeleted: boolean, userId: string, deviceId: string, }
