// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DocumentVersion {
    contentBase64: string;
    vaultUpdateId: number;
    documentId: string;
    updatedDate: string;
    userId: string;
    deviceId: string;
    contentSize: number;
}
