// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";
import type { Manifest } from "./Manifest";

export type EventRecord = { eventId: number; requestId: string } & (
    | { type: "content"; document: DocumentVersionWithoutContent }
    | { type: "manifest"; manifest: Manifest }
);
