// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventRecord } from "./EventRecord";

export type EventBatch = { headEventId: number, events: Array<EventRecord>, };
