// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventRecord } from "./EventRecord";

export type EventBatch = { headEventId: number, 
/**
 * Last event in this page; `head_event_id` is the vault's current head.
 */
endEventId?: number, events: Array<EventRecord>, };
