// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";

/**
 * Response to a fetch latest documents request.
 */
export interface FetchLatestDocumentsResponse {
	latestDocuments: DocumentVersionWithoutContent[];
	/**
	 * The update ID of the latest document in the response.
	 */
	lastUpdateId: bigint;
}
