// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to a ping request.
 */
export interface PingResponse {
	/**
	 * Semantic version of the server.
	 */
	serverVersion: string;
	/**
	 * Whether the client is authenticated based on the sent Authorization
	 * header.
	 */
	isAuthenticated: boolean;
}
