// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PushContent } from "./PushContent";

export type PushDocument = { requestId: string, parentVersionId: number | null, content: PushContent, };
