// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PushContent =
    | { type: "Snapshot"; value: string }
    | { type: "Diff"; value: (number | string)[] };
