// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server configuration and authentication status.
 */
export type ServerConfigResponse = { 
/**
 * Semantic version of the server.
 */
serverVersion: string, 
/**
 * Whether the client is authenticated based on the sent Authorization
 * header.
 */
isAuthenticated: boolean, 
/**
 * List of file extensions that are allowed to be merged.
 */
mergeableFileExtensions: Array<string>, 
/**
 * API version that must match exactly between the client
 * and server.
 */
supportedApiVersion: number, };
