// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateDocumentVersion = { parent_version_id: bigint, relative_path: string, content: Array<number>, };
