// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateDocumentVersion {
	parent_version_id: bigint;
	relative_path: string;
	content: number[];
}
