// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";

/**
 * Response to a vault history request (paginated).
 */
export interface VaultHistoryResponse { versions: DocumentVersionWithoutContent[], hasMore: boolean, }
