// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a single vault returned by the list-vaults endpoint.
 */
export interface VaultInfo {
    name: string;
    documentCount: number;
    createdAt: string | null;
}
