// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";
import type { Manifest } from "./Manifest";

export interface VaultSnapshot {
    headEventId: number;
    manifest: Manifest;
    documents: DocumentVersionWithoutContent[];
}
