// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionWithoutContent } from "./DocumentVersionWithoutContent";
import type { FileManifest } from "./FileManifest";

export type VaultEvent = { "type": "content", document: DocumentVersionWithoutContent, } | { "type": "fileManifest", fileManifest: FileManifest, };
