// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rename notification. Emitted whenever a write commits a document at
 * a path that differs from what the origin client sent and/or from the
 * document's previous stored path. Unlike [`WebSocketVaultUpdate`] this
 * event is delivered to all subscribers *including the origin device*,
 * because the create/update HTTP response no longer carries the path and
 * the origin needs this event to learn the server-canonical path
 * (e.g. when the server deduped or rejected a rename).
 */
export interface WebSocketVaultPathChange { vaultUpdateId: number, documentId: string, relativePath: string, }
