// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WebSocketHandshake {
	token: string;
	deviceId: string;
	lastSeenVaultUpdateId: number | null;
}
