// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorPositionFromServer } from "./CursorPositionFromServer";
import type { WebSocketVaultUpdate } from "./WebSocketVaultUpdate";

export type WebSocketServerMessage =
	| ({ type: "vaultUpdate" } & WebSocketVaultUpdate)
	| ({ type: "cursorPositions" } & CursorPositionFromServer);
