// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorPositionFromClient } from "./CursorPositionFromClient";
import type { WebSocketHandshake } from "./WebSocketHandshake";

export type WebSocketClientMessage =
	| ({ type: "handshake" } & WebSocketHandshake)
	| ({ type: "cursorPositions" } & CursorPositionFromClient);
