name: E2E tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '*/30 * * * *'

concurrency:
  group: e2e-tests
  cancel-in-progress: false

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"
          check-latest: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.89.0"
          components: clippy, rustfmt

      - name: Setup rust
        run: |
          cargo install sqlx-cli
          cd sync-server
          sqlx database create --database-url sqlite://db.sqlite3
          sqlx migrate run --source src/app_state/database/migrations --database-url sqlite://db.sqlite3

      - name: E2E tests
        run: |
          cd sync-server
          cargo run config-e2e.yml --color never &
          cd ..

          scripts/e2e.sh 16

      - name: Cleanup
        if: always()
        run: scripts/clean-up.sh
