// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateDocumentVersion = {
    relative_path: string;
    last_seen_vault_update_id: number;
    content: Array<number>;
};
