// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultInfo } from "./VaultInfo";

/**
 * Response to listing vaults accessible to the authenticated user.
 */
export type ListVaultsResponse = {
    vaults: Array<VaultInfo>;
    hasMore: boolean;
    userName: string;
};
